---
# tasks file for roles/sample-apache

- name: installing packages
  yum:
    name:
      - httpd
      - mod_ssl
      - php
    state: latest

- name: enabling httpd service
  service: 
    name: httpd
    enabled: yes
    state: started

- name: opening firewall port
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items:
    - https
    - http

- name: creating web page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: 0755
  notify: restart apache

