#!/bin/bash


sudo ansible all -m user -a "name=automation state=present generate_ssh_key=yes" -u root

sudo ansible all -m copy -a "src=/home/automation/.ssh/id_rsa.pub dest=/home/automation/.ssh/id_rsa.pub owner=automation group=automation mode=0600" -u root

sudo ansible all -m copy -a 'content="automation ALL=(ALL) NOPASSWD: ALL" dest=/etc/sudoers.d/automation' -u root

