---
- hosts: database
  become: yes
  tasks: 
  - name: task 15
    file:
      state: directory 
      path: /etc/ansible/facts.d/

  - copy:
      content: |
        [sample_exam] 
        server_role=mysql
      dest: /etc/ansible/facts.d/custom.fact

