---
- hosts: proxy
  become: yes
  tasks:
  - name: setting motd
    copy:
      content: "Welcome to HAProxy server"
      dest: /etc/motd

- hosts: webservers
  become: yes
  tasks:
  - name: setting motd
    copy:
      content: "Welcome to Apache server"
      dest: /etc/motd

- hosts: database
  become: yes
  tasks:
  - name: setting motd
    copy:
      content: "Welcome to MySQL server"
      dest: /etc/motd

