---
- hosts: database
  become: yes
  tasks:
  - name: adding mysql repo
    yum_repository:
      name: mysql56-community
      description: "MySQL 5.6 YUM Repo"
      baseurl: http://repo.mysql.com/yum/mysql-5.6-community/el/7/x86_64/
      enabled: yes
      gpgcheck: yes
      gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
