---
- hosts: all
  become: yes
  tasks: 
  - name: setting params
    sysctl:
      name: vm.swappiness
      reload: yes
      value: '10'
    when: ansible_facts.['ansible_memtotal_mb']|int > 2048

  - debug:
      msg: "Server memory less than 2048MB"
    when: ansible_facts.ansible_memtotal_mb|int < 2048
