---
- hosts: all
  tasks:
  - name: Display all variables/facts known for a host
    debug:
      var: hostvars[inventory_hostname]['ansible_facts']['fqdn']
    when: inventory_hostname in groups['database']
    tags: err
