---
- hosts: database
  become: yes
  tasks: 
  - name: task 14
    copy:
      content: "dev,test,qa,prod"
      dest: /mnt/mysql_backups/database_list.txt
  - archive:
      path: /mnt/mysql_backups/database_list.txt
      format: gz
      dest: /mnt/mysql_backups/archive.gz
