---
- hosts: proxy
  become: yes
  gather_facts: no
  tasks:
  - name: creating job
    copy:
      content: date > /var/log/time.log
      dest: /etc/cron.hourly/time-job
      mode: 0755

  - name: Install necessary packages (DEBIAN)
    package: 
      name: '{{ item }}'
      state: latest
    with_items:
    - git
    - wget
    - tree
    - vim
    - ufw
    - build-essential 
    - libssl-dev
    - libffi-dev
    - python-dev
    - python-pip
    - net-tools
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Install necessary packages (RHEL)
    package:
    with_items:
    - git
    - wget
    - tree
    - vim
    - gcc 
    - libffi-devel
    - python-devel
    - openssl-devel
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
