---
- hosts: all
  become: yes
  tasks:
  - name: setting banner location
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^Banner'
      line: "Banner /etc/motd"

  - name: setting X11Forwarding
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^X11Forwarding'
      line: "X11Forwarding yes"

  - name: setting MaxAuthTries
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^MaxAuthTries'
      line: "MaxAuthTries 3"

