---
- hosts: database
  become: yes
  vars_files:
  - vars/user_list.yml
  - secret.yml
  gather_facts: no
  tasks:
  - name: creating users on database server
    user:
      name: "{{ item.username }}"
      uid: "{{ item.uid }}"
      password: "{{ user_password | password_hash('sha512') }}"
      generate_ssh_key: yes
      groups: wheel
      shell: /bin/bash
    loop: "{{ users }}"
    when: "{{ item.uid|string|first }} == 2"
  - copy:
      src: /home/automation/.ssh/id_rsa.pub
      dest: /home/{{item.username}}/.ssh/authorized.keys
      mode: 0600
      owner: "{{ item.username }}"
      group: "{{ item.username }}"
    loop: "{{ users }}"
    when: "{{ item.uid|string|first }} == 2"

- hosts: webservers
  become: yes
  vars_files:
  - vars/user_list.yml
  - secret.yml
  gather_facts: no
  tasks:
  - name: creating users on database server
    user:
      name: "{{ item.username }}"
      uid: "{{ item.uid }}"
      password: "{{ user_password | password_hash('sha512') }}"
      generate_ssh_key: yes
      groups: wheel
      shell: /bin/bash
    loop: "{{ users }}"
    when: "{{ item.uid|string|first }} == 1"

  - copy:
      src: /home/automation/.ssh/id_rsa.pub
      dest: /home/{{item.username}}/.ssh/authorized.keys
      mode: 0600
      owner: "{{ item.username }}"
      group: "{{ item.username }}"
    loop: "{{ users }}"
    when: "{{ item.uid|string|first }} == 1"

