---
- name: Crea un Pod utilizando Ansible
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: mypod-from-ansible
        namespace: ansible-playground
      spec:
        containers:
        - name: mycontainer
          image: "{{ image }}"
